name: app
description: "LearnSnap Kids"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.8.0
  flutter_secure_storage: ^9.2.4
  provider: ^6.1.5
  image_picker: ^1.1.2
  camera: ^0.11.1
  uuid: ^4.5.1
  video_player: ^2.9.3
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
